onServer/blog/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.blogger, name='alle_blogger'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.blog_list, name='blog_list')
]

onServer/django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^butikk/', include('store.urls', namespace='shop')),
    url(r'^betaling/', include('jstripe.urls', namespace='stripe')),
    url(r'^', include('home.urls')),
    url(r'^blogg/', include('blog.urls', namespace='blog')),
    url(r'^summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onServer/home/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView, DetailView
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='home_page'),
    url(r'^handlekurv/$', views.show, name='show'),
    url(r'^remove/$', views.remove_post, name='remove'),
    url(r'^removenum/$', views.remove_num, name='remove_num'),
    url(r'add_post/$', views.add_post, name='add_post'),
    ]

onServer/jstripe/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^kort$', views.payment, name='payment')
]

onServer/payments/urls.py
'''
This module is responsible for automatic processing of provider callback
data (asynchronous transaction updates).
'''
from __future__ import unicode_literals

from django.conf.urls import url
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
try:
    from django.db.transaction import atomic
except ImportError:
    def atomic(func):
        return func

from . import get_payment_model
from .core import provider_factory


@csrf_exempt
@atomic
def process_data(request, token, provider=None):
    '''
    Calls process_data of an appropriate provider.

    Raises Http404 if variant does not exist.
    '''
    Payment = get_payment_model()
    payment = get_object_or_404(Payment, token=token)
    if not provider:
        try:
            provider = provider_factory(payment.variant)
        except ValueError:
            raise Http404('No such payment')
    return provider.process_data(payment, request)


@csrf_exempt
@atomic
def static_callback(request, variant):

    try:
        provider = provider_factory(variant)
    except ValueError:
        raise Http404('No such provider')

    token = provider.get_token_from_request(request=request, payment=None)
    if not token:
        raise Http404('Invalid response')
    return process_data(request, token, provider)


urlpatterns = [
    url(r'^process/(?P<token>[0-9a-z]{8}-[0-9a-z]{4}-'
        '[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})/$', process_data,
        name='process_payment'),
    url(r'^process/(?P<variant>[a-z-]+)/$', static_callback,
        name='static_process_payment')]

onServer/sql/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^butikk/', include('store.urls', namespace='shop')),
    url(r'^betaling/', include('jstripe.urls', namespace='stripe')),
    url(r'^', include('home.urls')),
    url(r'^blogg/', include('blog.urls', namespace='blog')),
    url(r'^summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onServer/store/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView, DetailView
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^add/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.add, name='add'),
]

onServer/payments/authorizenet/forms.py
from __future__ import unicode_literals

from ..forms import CreditCardPaymentForm
from .. import PaymentStatus

RESPONSE_STATUS = {
    '1': PaymentStatus.CONFIRMED,
    '2': PaymentStatus.REJECTED}


class PaymentForm(CreditCardPaymentForm):

    def clean(self):
        cleaned_data = super(PaymentForm, self).clean()

        if not self.errors:
            if not self.payment.transaction_id:
                data = {
                    'x_card_num': cleaned_data.get('number'),
                    'x_exp_date': cleaned_data.get('expiration'),
                    'x_card_code': cleaned_data.get('cvv2')}
                response = self.provider.get_payment_response(
                    self.payment, data)
                data = response.text.split('|')
                if response.ok and RESPONSE_STATUS.get(data[0], False):
                    status = RESPONSE_STATUS.get(data[0], PaymentStatus.ERROR)
                    self.payment.transaction_id = data[6]
                    if status == PaymentStatus.CONFIRMED:
                        self.payment.captured_amount = self.payment.total
                    self.payment.change_status(status)
                else:
                    errors = [data[3]]
                    self._errors['__all__'] = self.error_class(errors)
                    self.payment.change_status(PaymentStatus.ERROR)
        return cleaned_data

onServer/payments/braintree/forms.py
from __future__ import unicode_literals

import braintree

from ..forms import CreditCardPaymentFormWithName
from .. import PaymentStatus


class BraintreePaymentForm(CreditCardPaymentFormWithName):

    transaction_id = None

    def clean(self):
        data = self.cleaned_data

        if not self.errors and not self.payment.transaction_id:
            result = braintree.Transaction.sale({
                'amount': str(self.payment.total),
                'billing': self.get_billing_data(),
                'credit_card': self.get_credit_card_clean_data(),
                'customer': self.get_customer_data(),
                'options': {
                    'submit_for_settlement': False},
                'order_id': self.payment.description})

            if result.is_success:
                self.transaction_id = result.transaction.id
            else:
                self._errors['__all__'] = self.error_class([result.message])
                self.payment.change_status(PaymentStatus.ERROR)

        return data

    def get_credit_card_clean_data(self):
        if self.cleaned_data:
            return {
                'number': self.cleaned_data.get('number'),
                'cvv': self.cleaned_data.get('cvv2'),
                'cardholder_name': self.cleaned_data.get('name'),
                'expiration_month': self.cleaned_data.get('expiration').month,
                'expiration_year': self.cleaned_data.get('expiration').year}

    def get_billing_data(self):
        return {
            'first_name': self.payment.billing_first_name,
            'last_name': self.payment.billing_last_name,
            'street_address': self.payment.billing_address_1,
            'extended_address': self.payment.billing_address_2,
            'locality': self.payment.billing_city,
            'region': self.payment.billing_country_area,
            'postal_code': self.payment.billing_postcode,
            'country_code_alpha2': self.payment.billing_country_code}

    def get_customer_data(self):
        return {
            'first_name': self.payment.billing_first_name,
            'last_name': self.payment.billing_last_name}

    def save(self):
        braintree.Transaction.submit_for_settlement(self.transaction_id)
        self.payment.transaction_id = self.transaction_id
        self.payment.captured_amount = self.payment.total
        self.payment.change_status(PaymentStatus.CONFIRMED)

onServer/payments/cybersource/forms.py
from __future__ import unicode_literals

from uuid import uuid4

from django import forms
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _

from .. import PaymentError
from ..forms import CreditCardPaymentFormWithName


class FingerprintWidget(forms.HiddenInput):

    def render(self, name, value, attrs=None):
        final_attrs = dict(attrs or {}, type=self.input_type, name=name)
        final_attrs.update(self.attrs)
        final_attrs['session_id'] = value
        return render_to_string(
            'payments/cybersource_fingerprint.html', final_attrs)


class FingerprintInput(forms.CharField):

    widget = FingerprintWidget
    hidden_widget = FingerprintWidget

    def __init__(self, org_id, merchant_id, fingerprint_url,  *args, **kwargs):
        self.org_id = org_id
        self.merchant_id = merchant_id
        self.fingerprint_url = fingerprint_url
        super(FingerprintInput, self).__init__(*args, **kwargs)

    def widget_attrs(self, widget):
        attrs = super(FingerprintInput, self).widget_attrs(widget=widget)
        attrs['org_id'] = self.org_id
        attrs['merchant_id'] = self.merchant_id
        attrs['fingerprint_url'] = self.fingerprint_url
        return attrs


class PaymentForm(CreditCardPaymentFormWithName):

    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        if self.provider.org_id:
            try:
                fingerprint_id = self.payment.attrs.fingerprint_session_id
            except KeyError:
                fingerprint_id = str(uuid4())
            self.fields['fingerprint'] = FingerprintInput(
                label=_('fingerprint'), org_id=self.provider.org_id,
                initial=fingerprint_id,
                merchant_id=self.provider.merchant_id,
                fingerprint_url=self.provider.fingerprint_url)

    def clean(self):
        cleaned_data = super(PaymentForm, self).clean()
        if not self.errors:
            if self.provider.org_id:
                fingerprint = cleaned_data['fingerprint']
                self.payment.attrs.fingerprint_session_id = fingerprint
            if not self.payment.transaction_id:
                try:
                    self.provider.charge(self.payment, cleaned_data)
                except PaymentError as e:
                    self._errors['__all__'] = self.error_class([e.args[0]])
            else:
                msg = _('This payment has already been processed.')
                self._errors['__all__'] = self.error_class([msg])
        return cleaned_data

onServer/payments/dotpay/forms.py
from __future__ import unicode_literals
import hashlib

from django import forms

from .. import PaymentStatus


NO_MORE_CONFIRMATION = 0
NEW = 1
ACCEPTED = 2
REJECTED = 3
CANCELED = 4

STATUS_CHOICES = map(lambda c: (c, c), (
    NO_MORE_CONFIRMATION,
    NEW,
    ACCEPTED,
    REJECTED,
    CANCELED
))


class ProcessPaymentForm(forms.Form):

    status = forms.ChoiceField(choices=(('OK', 'OK'), ('FAIL', 'FAIL')))
    id = forms.IntegerField()
    control = forms.IntegerField()
    t_id = forms.CharField()
    amount = forms.DecimalField()
    email = forms.EmailField(required=False)
    t_status = forms.TypedChoiceField(coerce=int, choices=STATUS_CHOICES)
    description = forms.CharField(required=False)
    md5 = forms.CharField()

    def __init__(self, payment, pin, **kwargs):
        super(ProcessPaymentForm, self).__init__(**kwargs)
        self.pin = pin
        self.payment = payment

    def clean(self):
        cleaned_data = super(ProcessPaymentForm, self).clean()
        if not self.errors:
            key_vars = (
                self.pin,
                str(cleaned_data['id']),
                str(cleaned_data['control']),
                str(cleaned_data['t_id']),
                str(cleaned_data['amount']),
                cleaned_data.get('email', ''),
                '',  # service
                '',  # code
                '',  # username
                '',  # password
                str(cleaned_data['t_status']))
            key = ':'.join(key_vars)
            md5 = hashlib.md5()
            md5.update(key.encode('utf-8'))
            key_hash = md5.hexdigest()
            if key_hash != self.cleaned_data['md5']:
                self._errors['md5'] = self.error_class(['Bad hash'])
            if cleaned_data['control'] != self.payment.id:
                self._errors['control'] = self.error_class(['Bad payment id'])
        return cleaned_data

    def save(self, *args, **kwargs):
        status = self.cleaned_data['t_status']
        self.payment.transaction_id = self.cleaned_data['t_id']
        self.payment.save()
        payment_status = self.payment.status
        if status == ACCEPTED:
            self.payment.captured_amount = self.payment.total
            self.payment.change_status(PaymentStatus.CONFIRMED)
        elif ((status == NO_MORE_CONFIRMATION and payment_status == PaymentStatus.WAITING)
              or status == REJECTED or status == CANCELED):
            self.payment.change_status(PaymentStatus.REJECTED)

onServer/payments/jstripe/forms.py
from .models import Order
from django.forms import ModelForm
from django.core.exceptions import NON_FIELD_ERRORS

class OrderForm(ModelForm):


    class Meta:
        model = Order
        fields = ('fornavn', 'etternavn','epost', 'addresse','postnummer','poststed', 'token', 'beskrivelse', 'sendt')

    def add_error(self, message, *args):
        self._errors[NON_FIELD_ERRORS] = self.error_class([message])

onServer/payments/jstripe/views.py
from django.shortcuts import render, HttpResponse
from .forms import OrderForm
from store.models import Product
import stripe
from carton.cart import Cart

stripe.api_key = 'sk_live_mCzZJGhishO3nszTbYWgy7oG'
def payment(request):
    cart = Cart(request.session)
    total = cart.total

    if request.method == 'POST':
        ting = ''
        for item in cart.items:
            ting = ting+'\n'+str(item.quantity)+' av '+item.product.name

        mutable = request.POST._mutable
        request.POST._mutable = True
        request.POST['beskrivelse']= ting
        request.POST._mutable = mutable

        form = OrderForm(request.POST)

        if form.is_valid():
            token = form.cleaned_data['token']

            try:
                stripe.Charge.create(
                    amount = int(total*100),
                    currency = "nok",
                    description = ""+form.cleaned_data['etternavn']+", "+form.cleaned_data['fornavn'],
                    source = token,
                    )
                for item in cart.items:
                    vare = Product.objects.get(id=item.product.id)
                    if vare.stock >= item.quantity:
                        vare.stock -= item.quantity
                    else:
                        vare.stock = 0
                    vare.solgt += item.quantity
                    vare.save()

                form.save()
                args = {}
                args['fornavn'] = form.cleaned_data['fornavn']
                args['etternavn'] = form.cleaned_data['etternavn']
                args['addresse'] = form.cleaned_data['addresse']
                args['postnummer'] = form.cleaned_data['postnummer']
                args['poststed'] = form.cleaned_data['poststed']
                cart.clear()
                return render(request, 'virk.html', args)

            except stripe.CardError as e:
                form.add_error("Kortet ble ikke akseptert")
    else:
        form = OrderForm(request.POST)

    return render(request, 'stripe.html', {'form':form})

onServer/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from .models import Category, Product, Image
from carton.cart import Cart

# Create your views here.
def product_list(request, category_slug=None):
    category= None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'store.html', {'category': category,
                                          'categories': categories,
                                          'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    image = Image.objects.filter(product=product)
    #cart_product_form = CartAddProductForm()
    return render(request, 'store-detail.html', {'product':product,'image':image})#'cart_product_form': cart_product_form})

def add(request, id, slug):
    cart = Cart(request.session)
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart.add(product, price=product.price)
    return redirect(product)

def show(request):
    cart = Cart(request.session)
    total = cart.total
    return render(request, 'cart.html', {'total': total,})

onServer/store/templates/andre.html
{% load cat %}

<div class="dropdown">
  {% for catog in catogery %}
    <div class="cont"><a href="{{ catog.get_absolute_url }}">{{ catog.name }}</a></div>
  {% endfor %}
</div>

onServer/store/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!--<link rel="stylesheet" href="main.css">-->
	{% load static %}
	  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <title>{% block title %}{% endblock %}Fengslende Gaver</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="{% block des %}Fengslende Gaver videre selger varer produsert i fengsel.{% endblock %}">

    <meta name="og:title" content="{% block tit %}Fengslendegaver {% endblock %}">
    <meta name="og:description" content="{% block desf %}Fengslende Gaver videre selger varer produsert i fengsel.{% endblock %}">
    <meta name="og:image" content="{% block bilde %}/static/img/gave_logo.png{% endblock %}">
    {% block head %}
    {% endblock %}

  </head>
  <body>
    <nav>
      {% load cat %}
      {% load carton_tags %}
      {% get_cart as cart %}

      <div id="top">
          <div class="img">
            <a href="{% url 'home:home_page' %}">
              <img src="{% static 'img/gave_logo.png' %}" alt="Logoen til fengslende gaver" width="auto" height="auto">
            </a>
          </div>

          <ul>
            <li><a href="{% url 'shop:product_list' %}">Butikk</a></li>

            <li><a href="{% url 'blog:alle_blogger' %}">Blogg</a></li>

            <li>
              <div class="iconCart">
                <img src="{% static 'img/cart.svg' %}" alt="En handlekurv" width="auto" height="auto">
                {% if cart.count > 0 %}<icon>{{ cart.count }}</icon> {% endif %}
              </div>
            <div class="dropdown">
              {% for item in cart.items %}
              <ul class="cont">
                  <li>{{ item.product.name }}</li>
                  <li>{{ item.quantity }} stk</li>
                  <li>{{ item.subtotal }} kr</li>
                  <a href="{{ item.product.get_absolute_url }}"></a>
                </ul>
              {% endfor %}
              <ul class="cont link">
                <a href="{% url 'home:show' %}">Gå til handlekurven</a>
              </ul>
          </div>
          </li>
        </ul>

        <div class="wrapperWrapper">
          {% if cart.count > 0 %}<icon>{{ cart.count }}</icon> {% endif %}
        <div class="wrapper-menu">
          <div class="line-menu half start"></div>
          <div class="line-menu"></div>
          <div class="line-menu half end"></div>
        </div>
      </div>
      </div>

      <div class="dmenu">
        <ul>
          <li><a href="{% url 'blog:alle_blogger' %}">Blogg</a></li>
          <li><a href="{% url 'shop:product_list' %}">Butikk</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'tekstil' %}">Tekstil</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'glass' %}">Glass</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'bok' %}">Bok</a></li>


          <li>
            <div class="iconCart">
              {% if cart.count > 0 %}<icon>{{ cart.count }}</icon> {% endif %}
              <img src="{% static 'img/cart.svg' %}" alt="En handlekurv" width="auto" height="auto">
            </div>
          <div class="dropdown">
            {% for item in cart.items %}
            <ul class="cont">
                <li>{{ item.product.name }}</li>
                <li>{{ item.quantity }} stk</li>
                <li>{{ item.subtotal }} kr</li>
                <a href="{{ item.product.get_absolute_url }}"></a>
              </ul>
            {% endfor %}
            <ul class="cont link">
              <a href="{% url 'home:show' %}">Gå til handlekurven</a>
            </ul>
        </div>
        </li>
      </ul>

      </div>

    </nav>

    <div id="bunn">

        <ul>
          <li><a href="{% url 'shop:product_list_by_category' 'tekstil' %}">Tekstil</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'glass' %}">Glass</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'bok' %}">Bok</a></li>
          <li><p>Annet</p>

            {% cat %}
          </li>
          {% block navbar %}{% endblock %}
        </ul>
      </div>

    {% block body %}{% endblock %}

    <main>
    {% block main %}{% endblock %}
    </main>
    <footer>
      <h2>Alle varer er produsert av Fengslende Design</h2>

      <div class="list">

        <ul>
          <li><a href="{% url 'shop:product_list' %}">Butikk</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'tekstil' %}">Tekstil</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'glass' %}">Glass</a></li>
          <li><a href="{% url 'shop:product_list_by_category' 'bok' %}">Bok</a></li>
        </ul>

        <ul>
          <h3 style="margin-bottom:8px;">Om Fengslende Design</h3>
          <li>Addresse: Sonsgt 2</li>
        </ul>

      </div>

      <h3>&copy; Fengslende Gaver</h3>
      {% block footer %}{% endblock %}
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'scipt.js' %}"></script>
    <script>
    var wrapperMenu = document.querySelector('.wrapper-menu');
    var dmenu = document.querySelector('.dmenu');

    wrapperMenu.addEventListener('click', function(){
      wrapperMenu.classList.toggle('open');
      dmenu.classList.toggle('oppe');
    })
    </script>
    {% block script %}{% endblock %}
  </body>
</html>

onServer/store/templates/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ blogg.tittel }} |
{% endblock %}

{% block main %}
  <div class="blogg-datail">
    <h1>{{ blogg.tittel }}</h1>
    <img src="{% if blogg.bilde %}{{ blogg.bilde.url }}{% endif %}" alt="blogg bilde">
    <p class="date">{{ blogg.laget }}</p>
    <strong>{{ blogg.ingress|safe }}</strong>
    {{ blogg.hoveddel|safe|linebreaks }}
  </div>
{% endblock %}

<!--<form action="{% url "cart:cart_add" product.id %}" method="post">
  {{ cart_product_form }}
  {% csrf_token %}
  <input type="submit" value="Add to cart">
</form>-->

onServer/store/templates/blogger.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Blogg |
{% endblock %}

{% block main %}
  <div class="blogger">
    {% for blogg in blogger %}
    <div class="blog">

    <a href="{{ blogg.get_absolute_url }}">
    <div class="img" {% if blogg.bilde %} style="background-image: url({{ blogg.bilde.url }});"{% endif %}>
      <!--<img src="{% if blogg.bilde %}{{ blogg.bilde.url }}{% endif %}" alt="blogg bilde">-->
    </div>
    <div class="info">
      <h1>{{ blogg.tittel }}</h1>
      <p>{{ blogg.ingress|safe }}</p>
      </div>
    </div>
    </a>
    {% endfor %}
  </div>
{% endblock %}

<!--<form action="{% url "cart:cart_add" product.id %}" method="post">
  {{ cart_product_form }}
  {% csrf_token %}
  <input type="submit" value="Add to cart">
</form>-->

onServer/store/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Handlekurv |
{% endblock %}

{% block main %}
  {% load carton_tags %}
  {% get_cart as cart %}

    {% if nok %}{% else %}<p class="tek" style="color: #f00;">Vi har ikke nok av en vare</p>{% endif %}

  {% if cart.items %}
  <div class="cart">
    <div class="mob">
      <a href="{% if nok %}{% url 'stripe:payment' %}{% endif %}">Betal</a>
    </div>
    {% endif %}

  {% for item in cart.items %}
  <div class="item">

        <a href="{{ item.product.get_absolute_url }}">
        </a>
        <div class="img">

          <img src="{% if item.product.image %}{{ item.product.image.url }}{% endif %}" alt="product bilde">
        </div>

      <div class="panel">

        <h2>{{ item.product.name }}</h2>
        <p>{{ item.price }} kr hver</p>
        <p>{{ item.quantity }} stk</p>
        <p>{{ item.subtotal }} kr</p>
        {% if item.product.stock >=  item.quantity  %}<p class="tek" style="color: #0f0;">Nok på lager</p>{% else %}<p class="tek" style="color: #f00;">Vi har kun {{item.product.stock}}</p>{% endif %}

        <form id="num" action="{% url 'home:remove_num' %}" method="get">
          {% csrf_token %}
          <input type="hidden" name="antall" value="{{ item.quantity }}">
          <input type="number" name="num" value="1">
          <input type="hidden" name="product_id" value="{{ item.product.id }}">
          <input type="submit" name="fjern" value="fjern">
        </form>

        <form id="for" action="{% url 'home:remove' %}" method="get">
          {% csrf_token %}
          <input type="hidden" name="product_id" value="{{ item.product.id }}">
          <input type="submit" name="fjern" value="fjern alle">
        </form>
      </div>
    </div>

  {% endfor %}
  <div class="sum">
    {% if cart.items %}
    <a href="{% if nok %}{% url 'stripe:payment' %}{% endif %}">Betal</a>
    {% endif %}

    <h4>Sum: {{ total }} kr</h4>

  </div>
  </div>

{% endblock %}

onServer/store/templates/store-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ product.name }} |
{% endblock %}

{% block main %}
  <div class="product-detail">
    <div class="img">
      <img class="show" src="{% if product.image %}{{ product.image.url }}{% endif %}" alt="product bilde">
      {% if image %}
        {% for im in image %}
        <img src="{{ im.image.url }}" alt="product bilde">
        {% endfor %}
      {% endif %}
    </div>

    <div class="panel">

      <h1>{{ product.name }}</h1>
      <div class="des">
        {{ product.description|safe|linebreaks }}
      </div>

      {% if product.stock == 0 %}<h3 style="color:red;">Ingen igjen</h3>{% elif product.stock <  5  %}<h3>Kun {{ product.stock }} igjen</h3>{% endif %}

      <p class="price">{{ product.price }} kr</p>
      <h2><a href="{{ product.category.get_absolute_url }}">Kategori: {{ product.category }}</a></h2>

      <div class="cart">
        <a href="{% if product.stock > 0  %}{{ product.get_cart_url }}{% endif %}">Legg til i Handlekurven</a>
      </div>
    </div>

  </div>
{% endblock %}

<!--<form action="{% url "cart:cart_add" product.id %}" method="post">
  {{ cart_product_form }}
  {% csrf_token %}
  <input type="submit" value="Add to cart">
</form>


<form action="{% url "shop:add" %}" method="get">
  {% csrf_token %}
  <input type="number" name="product_id" value="{{ product.id }}">
  <input type="submit" value="Add to cart">
</form>-->

onServer/store/templates/total.html
{% load cat %}

{{ cost }}

onServer/store/templates/virk.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Fullført |
{% endblock %}

{% block head %}
  <style>
  main {
    margin: 0;
    background-image: url(/static/img/glass.jpg);
    width: 100%;
    height: 700px;
    background-size: cover;
    background-repeat: no-repeat;
    display: flex;
    max-width: 100vw;
    background-position: center;
    max-height: 90vh;
  }
  </style>
{% endblock %}



{% block main %}


  <div class="suctek">
    <h1>Takk {{fornavn}} {{etternavn}},</h1>
    <h3>Bestillingen er mottatt og blir sendt til {{addresse}}, {{postnummer}} {{poststed}}</h3>

    <a href="{% url 'home:home_page' %}">Gå hjem</a>

  </div>
{% endblock %}